[package]
name = "build_no_std"
version = "0.1.0"
authors = ["Jing Yanqing <yanqing.jing@osim.com.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mqtt-sys = { path = "mqtt-sys"}

